# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "protocols"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "23.5.26"

[lints.rust]
unused = "allow"
unsafe_code = "allow"
