// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterDataRow : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static CharacterDataRow GetRootAsCharacterDataRow(ByteBuffer _bb) { return GetRootAsCharacterDataRow(_bb, new CharacterDataRow()); }
  public static CharacterDataRow GetRootAsCharacterDataRow(ByteBuffer _bb, CharacterDataRow obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterDataRow __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public Proto.StatProp? Props(int j) { int o = __p.__offset(8); return o != 0 ? (Proto.StatProp?)(new Proto.StatProp()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PropsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Proto.SkillType CastSkill { get { int o = __p.__offset(10); return o != 0 ? (Proto.SkillType)__p.bb.GetInt(o + __p.bb_pos) : Proto.SkillType.NONE; } }
  public Proto.SkillType SpecialSkill { get { int o = __p.__offset(12); return o != 0 ? (Proto.SkillType)__p.bb.GetInt(o + __p.bb_pos) : Proto.SkillType.NONE; } }
  public int BulletGenCd { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BulletBufferSize { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Proto.CharacterDataRow> CreateCharacterDataRow(FlatBufferBuilder builder,
      int id = 0,
      StringOffset nameOffset = default(StringOffset),
      VectorOffset propsOffset = default(VectorOffset),
      Proto.SkillType cast_skill = Proto.SkillType.NONE,
      Proto.SkillType special_skill = Proto.SkillType.NONE,
      int bullet_gen_cd = 0,
      int bullet_buffer_size = 0) {
    builder.StartTable(7);
    CharacterDataRow.AddBulletBufferSize(builder, bullet_buffer_size);
    CharacterDataRow.AddBulletGenCd(builder, bullet_gen_cd);
    CharacterDataRow.AddSpecialSkill(builder, special_skill);
    CharacterDataRow.AddCastSkill(builder, cast_skill);
    CharacterDataRow.AddProps(builder, propsOffset);
    CharacterDataRow.AddName(builder, nameOffset);
    CharacterDataRow.AddId(builder, id);
    return CharacterDataRow.EndCharacterDataRow(builder);
  }

  public static void StartCharacterDataRow(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddProps(FlatBufferBuilder builder, VectorOffset propsOffset) { builder.AddOffset(2, propsOffset.Value, 0); }
  public static VectorOffset CreatePropsVector(FlatBufferBuilder builder, Offset<Proto.StatProp>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePropsVectorBlock(FlatBufferBuilder builder, Offset<Proto.StatProp>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePropsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Proto.StatProp>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePropsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Proto.StatProp>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPropsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddCastSkill(FlatBufferBuilder builder, Proto.SkillType castSkill) { builder.AddInt(3, (int)castSkill, 0); }
  public static void AddSpecialSkill(FlatBufferBuilder builder, Proto.SkillType specialSkill) { builder.AddInt(4, (int)specialSkill, 0); }
  public static void AddBulletGenCd(FlatBufferBuilder builder, int bulletGenCd) { builder.AddInt(5, bulletGenCd, 0); }
  public static void AddBulletBufferSize(FlatBufferBuilder builder, int bulletBufferSize) { builder.AddInt(6, bulletBufferSize, 0); }
  public static Offset<Proto.CharacterDataRow> EndCharacterDataRow(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.CharacterDataRow>(o);
  }
  public CharacterDataRowT UnPack() {
    var _o = new CharacterDataRowT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CharacterDataRowT _o) {
    _o.Id = this.Id;
    _o.Name = this.Name;
    _o.Props = new List<Proto.StatPropT>();
    for (var _j = 0; _j < this.PropsLength; ++_j) {_o.Props.Add(this.Props(_j).HasValue ? this.Props(_j).Value.UnPack() : null);}
    _o.CastSkill = this.CastSkill;
    _o.SpecialSkill = this.SpecialSkill;
    _o.BulletGenCd = this.BulletGenCd;
    _o.BulletBufferSize = this.BulletBufferSize;
  }
  public static Offset<Proto.CharacterDataRow> Pack(FlatBufferBuilder builder, CharacterDataRowT _o) {
    if (_o == null) return default(Offset<Proto.CharacterDataRow>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _props = default(VectorOffset);
    if (_o.Props != null) {
      var __props = new Offset<Proto.StatProp>[_o.Props.Count];
      for (var _j = 0; _j < __props.Length; ++_j) { __props[_j] = Proto.StatProp.Pack(builder, _o.Props[_j]); }
      _props = CreatePropsVector(builder, __props);
    }
    return CreateCharacterDataRow(
      builder,
      _o.Id,
      _name,
      _props,
      _o.CastSkill,
      _o.SpecialSkill,
      _o.BulletGenCd,
      _o.BulletBufferSize);
  }
}

public class CharacterDataRowT
{
  public int Id { get; set; }
  public string Name { get; set; }
  public List<Proto.StatPropT> Props { get; set; }
  public Proto.SkillType CastSkill { get; set; }
  public Proto.SkillType SpecialSkill { get; set; }
  public int BulletGenCd { get; set; }
  public int BulletBufferSize { get; set; }

  public CharacterDataRowT() {
    this.Id = 0;
    this.Name = null;
    this.Props = null;
    this.CastSkill = Proto.SkillType.NONE;
    this.SpecialSkill = Proto.SkillType.NONE;
    this.BulletGenCd = 0;
    this.BulletBufferSize = 0;
  }
}


static public class CharacterDataRowVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Props*/, Proto.StatPropVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*CastSkill*/, 4 /*Proto.SkillType*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*SpecialSkill*/, 4 /*Proto.SkillType*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*BulletGenCd*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*BulletBufferSize*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
