// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientPushBattleAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static ClientPushBattleAction GetRootAsClientPushBattleAction(ByteBuffer _bb) { return GetRootAsClientPushBattleAction(_bb, new ClientPushBattleAction()); }
  public static ClientPushBattleAction GetRootAsClientPushBattleAction(ByteBuffer _bb, ClientPushBattleAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientPushBattleAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ActionType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ActionParams(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ActionParamsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetActionParamsBytes() { return __p.__vector_as_span<int>(6, 4); }
#else
  public ArraySegment<byte>? GetActionParamsBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public int[] GetActionParamsArray() { return __p.__vector_as_array<int>(6); }

  public static Offset<Proto.ClientPushBattleAction> CreateClientPushBattleAction(FlatBufferBuilder builder,
      int action_type = 0,
      VectorOffset action_paramsOffset = default(VectorOffset)) {
    builder.StartTable(2);
    ClientPushBattleAction.AddActionParams(builder, action_paramsOffset);
    ClientPushBattleAction.AddActionType(builder, action_type);
    return ClientPushBattleAction.EndClientPushBattleAction(builder);
  }

  public static void StartClientPushBattleAction(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddActionType(FlatBufferBuilder builder, int actionType) { builder.AddInt(0, actionType, 0); }
  public static void AddActionParams(FlatBufferBuilder builder, VectorOffset actionParamsOffset) { builder.AddOffset(1, actionParamsOffset.Value, 0); }
  public static VectorOffset CreateActionParamsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateActionParamsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateActionParamsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateActionParamsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartActionParamsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Proto.ClientPushBattleAction> EndClientPushBattleAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.ClientPushBattleAction>(o);
  }
  public ClientPushBattleActionT UnPack() {
    var _o = new ClientPushBattleActionT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientPushBattleActionT _o) {
    _o.ActionType = this.ActionType;
    _o.ActionParams = new List<int>();
    for (var _j = 0; _j < this.ActionParamsLength; ++_j) {_o.ActionParams.Add(this.ActionParams(_j));}
  }
  public static Offset<Proto.ClientPushBattleAction> Pack(FlatBufferBuilder builder, ClientPushBattleActionT _o) {
    if (_o == null) return default(Offset<Proto.ClientPushBattleAction>);
    var _action_params = default(VectorOffset);
    if (_o.ActionParams != null) {
      var __action_params = _o.ActionParams.ToArray();
      _action_params = CreateActionParamsVector(builder, __action_params);
    }
    return CreateClientPushBattleAction(
      builder,
      _o.ActionType,
      _action_params);
  }
}

public class ClientPushBattleActionT
{
  public int ActionType { get; set; }
  public List<int> ActionParams { get; set; }

  public ClientPushBattleActionT() {
    this.ActionType = 0;
    this.ActionParams = null;
  }
}


static public class ClientPushBattleActionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ActionType*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*ActionParams*/, 4 /*int*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
