// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

public enum EOTKind : sbyte
{
  None = 0,
  Damage = 1,
  Heal = 2,
  Buff = 3,
  Debuff = 4,
  Special = 5,
  Trigger = 6,
};


}
