// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

public enum EOTType : sbyte
{
  None = 0,
  Eliminate = 1,
  HitBack = 2,
  PowerUp = 3,
  Duration = 4,
  ATKPower = 5,
  Bleed = 6,
  BleedTrigger = 7,
};


}
