// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RequestBattleEnd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static RequestBattleEnd GetRootAsRequestBattleEnd(ByteBuffer _bb) { return GetRootAsRequestBattleEnd(_bb, new RequestBattleEnd()); }
  public static RequestBattleEnd GetRootAsRequestBattleEnd(ByteBuffer _bb, RequestBattleEnd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RequestBattleEnd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong WinCampRank(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(__p.__vector(o) + j * 8) : (ulong)0; }
  public int WinCampRankLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<ulong> GetWinCampRankBytes() { return __p.__vector_as_span<ulong>(4, 8); }
#else
  public ArraySegment<byte>? GetWinCampRankBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public ulong[] GetWinCampRankArray() { return __p.__vector_as_array<ulong>(4); }

  public static Offset<Proto.RequestBattleEnd> CreateRequestBattleEnd(FlatBufferBuilder builder,
      VectorOffset win_camp_rankOffset = default(VectorOffset)) {
    builder.StartTable(1);
    RequestBattleEnd.AddWinCampRank(builder, win_camp_rankOffset);
    return RequestBattleEnd.EndRequestBattleEnd(builder);
  }

  public static void StartRequestBattleEnd(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddWinCampRank(FlatBufferBuilder builder, VectorOffset winCampRankOffset) { builder.AddOffset(0, winCampRankOffset.Value, 0); }
  public static VectorOffset CreateWinCampRankVector(FlatBufferBuilder builder, ulong[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddUlong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateWinCampRankVectorBlock(FlatBufferBuilder builder, ulong[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWinCampRankVectorBlock(FlatBufferBuilder builder, ArraySegment<ulong> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWinCampRankVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<ulong>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartWinCampRankVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static Offset<Proto.RequestBattleEnd> EndRequestBattleEnd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.RequestBattleEnd>(o);
  }
  public RequestBattleEndT UnPack() {
    var _o = new RequestBattleEndT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RequestBattleEndT _o) {
    _o.WinCampRank = new List<ulong>();
    for (var _j = 0; _j < this.WinCampRankLength; ++_j) {_o.WinCampRank.Add(this.WinCampRank(_j));}
  }
  public static Offset<Proto.RequestBattleEnd> Pack(FlatBufferBuilder builder, RequestBattleEndT _o) {
    if (_o == null) return default(Offset<Proto.RequestBattleEnd>);
    var _win_camp_rank = default(VectorOffset);
    if (_o.WinCampRank != null) {
      var __win_camp_rank = _o.WinCampRank.ToArray();
      _win_camp_rank = CreateWinCampRankVector(builder, __win_camp_rank);
    }
    return CreateRequestBattleEnd(
      builder,
      _win_camp_rank);
  }
}

public class RequestBattleEndT
{
  public List<ulong> WinCampRank { get; set; }

  public RequestBattleEndT() {
    this.WinCampRank = null;
  }
}


static public class RequestBattleEndVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*WinCampRank*/, 8 /*ulong*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
