// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ResponseBattleEnd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static ResponseBattleEnd GetRootAsResponseBattleEnd(ByteBuffer _bb) { return GetRootAsResponseBattleEnd(_bb, new ResponseBattleEnd()); }
  public static ResponseBattleEnd GetRootAsResponseBattleEnd(ByteBuffer _bb, ResponseBattleEnd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResponseBattleEnd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartResponseBattleEnd(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Proto.ResponseBattleEnd> EndResponseBattleEnd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.ResponseBattleEnd>(o);
  }
  public ResponseBattleEndT UnPack() {
    var _o = new ResponseBattleEndT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ResponseBattleEndT _o) {
  }
  public static Offset<Proto.ResponseBattleEnd> Pack(FlatBufferBuilder builder, ResponseBattleEndT _o) {
    if (_o == null) return default(Offset<Proto.ResponseBattleEnd>);
    StartResponseBattleEnd(builder);
    return EndResponseBattleEnd(builder);
  }
}

public class ResponseBattleEndT
{

  public ResponseBattleEndT() {
  }
}


static public class ResponseBattleEndVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
