// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ResponseTimeSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static ResponseTimeSync GetRootAsResponseTimeSync(ByteBuffer _bb) { return GetRootAsResponseTimeSync(_bb, new ResponseTimeSync()); }
  public static ResponseTimeSync GetRootAsResponseTimeSync(ByteBuffer _bb, ResponseTimeSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResponseTimeSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong ClientTime { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong ServerTime { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<Proto.ResponseTimeSync> CreateResponseTimeSync(FlatBufferBuilder builder,
      ulong client_time = 0,
      ulong server_time = 0) {
    builder.StartTable(2);
    ResponseTimeSync.AddServerTime(builder, server_time);
    ResponseTimeSync.AddClientTime(builder, client_time);
    return ResponseTimeSync.EndResponseTimeSync(builder);
  }

  public static void StartResponseTimeSync(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddClientTime(FlatBufferBuilder builder, ulong clientTime) { builder.AddUlong(0, clientTime, 0); }
  public static void AddServerTime(FlatBufferBuilder builder, ulong serverTime) { builder.AddUlong(1, serverTime, 0); }
  public static Offset<Proto.ResponseTimeSync> EndResponseTimeSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.ResponseTimeSync>(o);
  }
  public ResponseTimeSyncT UnPack() {
    var _o = new ResponseTimeSyncT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ResponseTimeSyncT _o) {
    _o.ClientTime = this.ClientTime;
    _o.ServerTime = this.ServerTime;
  }
  public static Offset<Proto.ResponseTimeSync> Pack(FlatBufferBuilder builder, ResponseTimeSyncT _o) {
    if (_o == null) return default(Offset<Proto.ResponseTimeSync>);
    return CreateResponseTimeSync(
      builder,
      _o.ClientTime,
      _o.ServerTime);
  }
}

public class ResponseTimeSyncT
{
  public ulong ClientTime { get; set; }
  public ulong ServerTime { get; set; }

  public ResponseTimeSyncT() {
    this.ClientTime = 0;
    this.ServerTime = 0;
  }
}


static public class ResponseTimeSyncVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ClientTime*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*ServerTime*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
