// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerBroadcastBattleShouldFinish : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static ServerBroadcastBattleShouldFinish GetRootAsServerBroadcastBattleShouldFinish(ByteBuffer _bb) { return GetRootAsServerBroadcastBattleShouldFinish(_bb, new ServerBroadcastBattleShouldFinish()); }
  public static ServerBroadcastBattleShouldFinish GetRootAsServerBroadcastBattleShouldFinish(ByteBuffer _bb, ServerBroadcastBattleShouldFinish obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerBroadcastBattleShouldFinish __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong ServerTime { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<Proto.ServerBroadcastBattleShouldFinish> CreateServerBroadcastBattleShouldFinish(FlatBufferBuilder builder,
      ulong server_time = 0) {
    builder.StartTable(1);
    ServerBroadcastBattleShouldFinish.AddServerTime(builder, server_time);
    return ServerBroadcastBattleShouldFinish.EndServerBroadcastBattleShouldFinish(builder);
  }

  public static void StartServerBroadcastBattleShouldFinish(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddServerTime(FlatBufferBuilder builder, ulong serverTime) { builder.AddUlong(0, serverTime, 0); }
  public static Offset<Proto.ServerBroadcastBattleShouldFinish> EndServerBroadcastBattleShouldFinish(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.ServerBroadcastBattleShouldFinish>(o);
  }
  public ServerBroadcastBattleShouldFinishT UnPack() {
    var _o = new ServerBroadcastBattleShouldFinishT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerBroadcastBattleShouldFinishT _o) {
    _o.ServerTime = this.ServerTime;
  }
  public static Offset<Proto.ServerBroadcastBattleShouldFinish> Pack(FlatBufferBuilder builder, ServerBroadcastBattleShouldFinishT _o) {
    if (_o == null) return default(Offset<Proto.ServerBroadcastBattleShouldFinish>);
    return CreateServerBroadcastBattleShouldFinish(
      builder,
      _o.ServerTime);
  }
}

public class ServerBroadcastBattleShouldFinishT
{
  public ulong ServerTime { get; set; }

  public ServerBroadcastBattleShouldFinishT() {
    this.ServerTime = 0;
  }
}


static public class ServerBroadcastBattleShouldFinishVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ServerTime*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
