// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerBroadcastBattleStarted : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static ServerBroadcastBattleStarted GetRootAsServerBroadcastBattleStarted(ByteBuffer _bb) { return GetRootAsServerBroadcastBattleStarted(_bb, new ServerBroadcastBattleStarted()); }
  public static ServerBroadcastBattleStarted GetRootAsServerBroadcastBattleStarted(ByteBuffer _bb, ServerBroadcastBattleStarted obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerBroadcastBattleStarted __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong StartServerTime { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<Proto.ServerBroadcastBattleStarted> CreateServerBroadcastBattleStarted(FlatBufferBuilder builder,
      ulong start_server_time = 0) {
    builder.StartTable(1);
    ServerBroadcastBattleStarted.AddStartServerTime(builder, start_server_time);
    return ServerBroadcastBattleStarted.EndServerBroadcastBattleStarted(builder);
  }

  public static void StartServerBroadcastBattleStarted(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddStartServerTime(FlatBufferBuilder builder, ulong startServerTime) { builder.AddUlong(0, startServerTime, 0); }
  public static Offset<Proto.ServerBroadcastBattleStarted> EndServerBroadcastBattleStarted(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.ServerBroadcastBattleStarted>(o);
  }
  public ServerBroadcastBattleStartedT UnPack() {
    var _o = new ServerBroadcastBattleStartedT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerBroadcastBattleStartedT _o) {
    _o.StartServerTime = this.StartServerTime;
  }
  public static Offset<Proto.ServerBroadcastBattleStarted> Pack(FlatBufferBuilder builder, ServerBroadcastBattleStartedT _o) {
    if (_o == null) return default(Offset<Proto.ServerBroadcastBattleStarted>);
    return CreateServerBroadcastBattleStarted(
      builder,
      _o.StartServerTime);
  }
}

public class ServerBroadcastBattleStartedT
{
  public ulong StartServerTime { get; set; }

  public ServerBroadcastBattleStartedT() {
    this.StartServerTime = 0;
  }
}


static public class ServerBroadcastBattleStartedVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*StartServerTime*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
