// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SkillData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static SkillData GetRootAsSkillData(ByteBuffer _bb) { return GetRootAsSkillData(_bb, new SkillData()); }
  public static SkillData GetRootAsSkillData(ByteBuffer _bb, SkillData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifySkillData(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, SkillDataVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SkillData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Proto.SkillDataRow? Rows(int j) { int o = __p.__offset(4); return o != 0 ? (Proto.SkillDataRow?)(new Proto.SkillDataRow()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RowsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Proto.SkillData> CreateSkillData(FlatBufferBuilder builder,
      VectorOffset rowsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SkillData.AddRows(builder, rowsOffset);
    return SkillData.EndSkillData(builder);
  }

  public static void StartSkillData(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRows(FlatBufferBuilder builder, VectorOffset rowsOffset) { builder.AddOffset(0, rowsOffset.Value, 0); }
  public static VectorOffset CreateRowsVector(FlatBufferBuilder builder, Offset<Proto.SkillDataRow>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRowsVectorBlock(FlatBufferBuilder builder, Offset<Proto.SkillDataRow>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRowsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Proto.SkillDataRow>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRowsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Proto.SkillDataRow>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRowsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Proto.SkillData> EndSkillData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.SkillData>(o);
  }
  public static void FinishSkillDataBuffer(FlatBufferBuilder builder, Offset<Proto.SkillData> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSkillDataBuffer(FlatBufferBuilder builder, Offset<Proto.SkillData> offset) { builder.FinishSizePrefixed(offset.Value); }
  public SkillDataT UnPack() {
    var _o = new SkillDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SkillDataT _o) {
    _o.Rows = new List<Proto.SkillDataRowT>();
    for (var _j = 0; _j < this.RowsLength; ++_j) {_o.Rows.Add(this.Rows(_j).HasValue ? this.Rows(_j).Value.UnPack() : null);}
  }
  public static Offset<Proto.SkillData> Pack(FlatBufferBuilder builder, SkillDataT _o) {
    if (_o == null) return default(Offset<Proto.SkillData>);
    var _rows = default(VectorOffset);
    if (_o.Rows != null) {
      var __rows = new Offset<Proto.SkillDataRow>[_o.Rows.Count];
      for (var _j = 0; _j < __rows.Length; ++_j) { __rows[_j] = Proto.SkillDataRow.Pack(builder, _o.Rows[_j]); }
      _rows = CreateRowsVector(builder, __rows);
    }
    return CreateSkillData(
      builder,
      _rows);
  }
}

public class SkillDataT
{
  public List<Proto.SkillDataRowT> Rows { get; set; }

  public SkillDataT() {
    this.Rows = null;
  }
  public static SkillDataT DeserializeFromBinary(byte[] fbBuffer) {
    return SkillData.GetRootAsSkillData(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    SkillData.FinishSkillDataBuffer(fbb, SkillData.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


static public class SkillDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Rows*/, Proto.SkillDataRowVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
