// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

public enum StatPropType : sbyte
{
  Unknown = 0,
  HP = 1,
  Attack = 2,
};


}
