// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

public enum StatPropValueType : sbyte
{
  VAL = 0,
  MUL = 1,
};


}
