// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod proto {
  use super::*;
  mod request_time_sync_generated;
  pub use self::request_time_sync_generated::*;
  mod response_time_sync_generated;
  pub use self::response_time_sync_generated::*;
  mod request_enter_generated;
  pub use self::request_enter_generated::*;
  mod response_enter_generated;
  pub use self::response_enter_generated::*;
  mod player_info_generated;
  pub use self::player_info_generated::*;
  mod battle_camp_generated;
  pub use self::battle_camp_generated::*;
  mod server_broadcast_battle_start_generated;
  pub use self::server_broadcast_battle_start_generated::*;
  mod client_push_battle_load_progress_generated;
  pub use self::client_push_battle_load_progress_generated::*;
  mod server_broadcast_battle_load_progress_generated;
  pub use self::server_broadcast_battle_load_progress_generated::*;
  mod server_broadcast_battle_started_generated;
  pub use self::server_broadcast_battle_started_generated::*;
  mod client_push_battle_action_generated;
  pub use self::client_push_battle_action_generated::*;
  mod battle_action_generated;
  pub use self::battle_action_generated::*;
  mod server_broadcast_battle_action_generated;
  pub use self::server_broadcast_battle_action_generated::*;
  mod server_broadcast_battle_should_finish_generated;
  pub use self::server_broadcast_battle_should_finish_generated::*;
  mod request_battle_end_generated;
  pub use self::request_battle_end_generated::*;
  mod response_battle_end_generated;
  pub use self::response_battle_end_generated::*;
  mod server_broadcast_battle_finished_generated;
  pub use self::server_broadcast_battle_finished_generated::*;
  mod request_reconnect_generated;
  pub use self::request_reconnect_generated::*;
  mod response_reconnect_generated;
  pub use self::response_reconnect_generated::*;
  mod reconnected_battle_state_generated;
  pub use self::reconnected_battle_state_generated::*;
} // proto
