// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod proto {
  use super::*;
  mod request_time_sync_generated;
  pub use self::request_time_sync_generated::*;
  mod response_time_sync_generated;
  pub use self::response_time_sync_generated::*;
} // proto
