// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum BattleCampOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BattleCamp<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for BattleCamp<'a> {
  type Inner = BattleCamp<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> BattleCamp<'a> {
  pub const VT_CAMP_ID: flatbuffers::VOffsetT = 4;
  pub const VT_PLAYERS: flatbuffers::VOffsetT = 6;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.BattleCamp"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    BattleCamp { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args BattleCampArgs<'args>
  ) -> flatbuffers::WIPOffset<BattleCamp<'bldr>> {
    let mut builder = BattleCampBuilder::new(_fbb);
    if let Some(x) = args.players { builder.add_players(x); }
    builder.add_camp_id(args.camp_id);
    builder.finish()
  }

  pub fn unpack(&self) -> BattleCampT {
    let camp_id = self.camp_id();
    let players = self.players().map(|x| {
      x.iter().map(|t| t.unpack()).collect()
    });
    BattleCampT {
      camp_id,
      players,
    }
  }

  #[inline]
  pub fn camp_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(BattleCamp::VT_CAMP_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn players(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<PlayerInfo<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<PlayerInfo>>>>(BattleCamp::VT_PLAYERS, None)}
  }
}

impl flatbuffers::Verifiable for BattleCamp<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("camp_id", Self::VT_CAMP_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<PlayerInfo>>>>("players", Self::VT_PLAYERS, false)?
     .finish();
    Ok(())
  }
}
pub struct BattleCampArgs<'a> {
    pub camp_id: i32,
    pub players: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<PlayerInfo<'a>>>>>,
}
impl<'a> Default for BattleCampArgs<'a> {
  #[inline]
  fn default() -> Self {
    BattleCampArgs {
      camp_id: 0,
      players: None,
    }
  }
}

pub struct BattleCampBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> BattleCampBuilder<'a, 'b> {
  #[inline]
  pub fn add_camp_id(&mut self, camp_id: i32) {
    self.fbb_.push_slot::<i32>(BattleCamp::VT_CAMP_ID, camp_id, 0);
  }
  #[inline]
  pub fn add_players(&mut self, players: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<PlayerInfo<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(BattleCamp::VT_PLAYERS, players);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> BattleCampBuilder<'a, 'b> {
    let start = _fbb.start_table();
    BattleCampBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<BattleCamp<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for BattleCamp<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("BattleCamp");
      ds.field("camp_id", &self.camp_id());
      ds.field("players", &self.players());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct BattleCampT {
  pub camp_id: i32,
  pub players: Option<Vec<PlayerInfoT>>,
}
impl Default for BattleCampT {
  fn default() -> Self {
    Self {
      camp_id: 0,
      players: None,
    }
  }
}
impl BattleCampT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<BattleCamp<'b>> {
    let camp_id = self.camp_id;
    let players = self.players.as_ref().map(|x|{
      let w: Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();_fbb.create_vector(&w)
    });
    BattleCamp::create(_fbb, &BattleCampArgs{
      camp_id,
      players,
    })
  }
}
