// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PlayerInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PlayerInfo<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PlayerInfo<'a> {
  type Inner = PlayerInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PlayerInfo<'a> {
  pub const VT_PLAYER_ID: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_SEED: flatbuffers::VOffsetT = 8;
  pub const VT_OTHER_INFO: flatbuffers::VOffsetT = 10;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.PlayerInfo"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PlayerInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args PlayerInfoArgs<'args>
  ) -> flatbuffers::WIPOffset<PlayerInfo<'bldr>> {
    let mut builder = PlayerInfoBuilder::new(_fbb);
    builder.add_seed(args.seed);
    builder.add_player_id(args.player_id);
    if let Some(x) = args.other_info { builder.add_other_info(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> PlayerInfoT {
    let player_id = self.player_id();
    let name = self.name().map(|x| {
      x.to_string()
    });
    let seed = self.seed();
    let other_info = self.other_info().map(|x| {
      x.into_iter().collect()
    });
    PlayerInfoT {
      player_id,
      name,
      seed,
      other_info,
    }
  }

  #[inline]
  pub fn player_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(PlayerInfo::VT_PLAYER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PlayerInfo::VT_NAME, None)}
  }
  #[inline]
  pub fn seed(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(PlayerInfo::VT_SEED, Some(0)).unwrap()}
  }
  #[inline]
  pub fn other_info(&self) -> Option<flatbuffers::Vector<'a, i32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i32>>>(PlayerInfo::VT_OTHER_INFO, None)}
  }
}

impl flatbuffers::Verifiable for PlayerInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("player_id", Self::VT_PLAYER_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<u64>("seed", Self::VT_SEED, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i32>>>("other_info", Self::VT_OTHER_INFO, false)?
     .finish();
    Ok(())
  }
}
pub struct PlayerInfoArgs<'a> {
    pub player_id: u64,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub seed: u64,
    pub other_info: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i32>>>,
}
impl<'a> Default for PlayerInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    PlayerInfoArgs {
      player_id: 0,
      name: None,
      seed: 0,
      other_info: None,
    }
  }
}

pub struct PlayerInfoBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> PlayerInfoBuilder<'a, 'b> {
  #[inline]
  pub fn add_player_id(&mut self, player_id: u64) {
    self.fbb_.push_slot::<u64>(PlayerInfo::VT_PLAYER_ID, player_id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PlayerInfo::VT_NAME, name);
  }
  #[inline]
  pub fn add_seed(&mut self, seed: u64) {
    self.fbb_.push_slot::<u64>(PlayerInfo::VT_SEED, seed, 0);
  }
  #[inline]
  pub fn add_other_info(&mut self, other_info: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PlayerInfo::VT_OTHER_INFO, other_info);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> PlayerInfoBuilder<'a, 'b> {
    let start = _fbb.start_table();
    PlayerInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PlayerInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PlayerInfo<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PlayerInfo");
      ds.field("player_id", &self.player_id());
      ds.field("name", &self.name());
      ds.field("seed", &self.seed());
      ds.field("other_info", &self.other_info());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct PlayerInfoT {
  pub player_id: u64,
  pub name: Option<String>,
  pub seed: u64,
  pub other_info: Option<Vec<i32>>,
}
impl Default for PlayerInfoT {
  fn default() -> Self {
    Self {
      player_id: 0,
      name: None,
      seed: 0,
      other_info: None,
    }
  }
}
impl PlayerInfoT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<PlayerInfo<'b>> {
    let player_id = self.player_id;
    let name = self.name.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let seed = self.seed;
    let other_info = self.other_info.as_ref().map(|x|{
      _fbb.create_vector(x)
    });
    PlayerInfo::create(_fbb, &PlayerInfoArgs{
      player_id,
      name,
      seed,
      other_info,
    })
  }
}
