// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum RequestBattleEndOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RequestBattleEnd<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RequestBattleEnd<'a> {
  type Inner = RequestBattleEnd<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RequestBattleEnd<'a> {
  pub const VT_WIN_CAMP_RANK: flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.RequestBattleEnd"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RequestBattleEnd { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RequestBattleEndArgs<'args>
  ) -> flatbuffers::WIPOffset<RequestBattleEnd<'bldr>> {
    let mut builder = RequestBattleEndBuilder::new(_fbb);
    if let Some(x) = args.win_camp_rank { builder.add_win_camp_rank(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> RequestBattleEndT {
    let win_camp_rank = self.win_camp_rank().map(|x| {
      x.into_iter().collect()
    });
    RequestBattleEndT {
      win_camp_rank,
    }
  }

  #[inline]
  pub fn win_camp_rank(&self) -> Option<flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u64>>>(RequestBattleEnd::VT_WIN_CAMP_RANK, None)}
  }
}

impl flatbuffers::Verifiable for RequestBattleEnd<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u64>>>("win_camp_rank", Self::VT_WIN_CAMP_RANK, false)?
     .finish();
    Ok(())
  }
}
pub struct RequestBattleEndArgs<'a> {
    pub win_camp_rank: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u64>>>,
}
impl<'a> Default for RequestBattleEndArgs<'a> {
  #[inline]
  fn default() -> Self {
    RequestBattleEndArgs {
      win_camp_rank: None,
    }
  }
}

pub struct RequestBattleEndBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RequestBattleEndBuilder<'a, 'b> {
  #[inline]
  pub fn add_win_camp_rank(&mut self, win_camp_rank: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RequestBattleEnd::VT_WIN_CAMP_RANK, win_camp_rank);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RequestBattleEndBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RequestBattleEndBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RequestBattleEnd<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RequestBattleEnd<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RequestBattleEnd");
      ds.field("win_camp_rank", &self.win_camp_rank());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct RequestBattleEndT {
  pub win_camp_rank: Option<Vec<u64>>,
}
impl Default for RequestBattleEndT {
  fn default() -> Self {
    Self {
      win_camp_rank: None,
    }
  }
}
impl RequestBattleEndT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<RequestBattleEnd<'b>> {
    let win_camp_rank = self.win_camp_rank.as_ref().map(|x|{
      _fbb.create_vector(x)
    });
    RequestBattleEnd::create(_fbb, &RequestBattleEndArgs{
      win_camp_rank,
    })
  }
}
