// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum RequestTimeSyncOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RequestTimeSync<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RequestTimeSync<'a> {
  type Inner = RequestTimeSync<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RequestTimeSync<'a> {
  pub const VT_CLIENT_TIME: flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.RequestTimeSync"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RequestTimeSync { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RequestTimeSyncArgs
  ) -> flatbuffers::WIPOffset<RequestTimeSync<'bldr>> {
    let mut builder = RequestTimeSyncBuilder::new(_fbb);
    builder.add_client_time(args.client_time);
    builder.finish()
  }

  pub fn unpack(&self) -> RequestTimeSyncT {
    let client_time = self.client_time();
    RequestTimeSyncT {
      client_time,
    }
  }

  #[inline]
  pub fn client_time(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RequestTimeSync::VT_CLIENT_TIME, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for RequestTimeSync<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("client_time", Self::VT_CLIENT_TIME, false)?
     .finish();
    Ok(())
  }
}
pub struct RequestTimeSyncArgs {
    pub client_time: u64,
}
impl<'a> Default for RequestTimeSyncArgs {
  #[inline]
  fn default() -> Self {
    RequestTimeSyncArgs {
      client_time: 0,
    }
  }
}

pub struct RequestTimeSyncBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RequestTimeSyncBuilder<'a, 'b> {
  #[inline]
  pub fn add_client_time(&mut self, client_time: u64) {
    self.fbb_.push_slot::<u64>(RequestTimeSync::VT_CLIENT_TIME, client_time, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RequestTimeSyncBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RequestTimeSyncBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RequestTimeSync<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RequestTimeSync<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RequestTimeSync");
      ds.field("client_time", &self.client_time());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct RequestTimeSyncT {
  pub client_time: u64,
}
impl Default for RequestTimeSyncT {
  fn default() -> Self {
    Self {
      client_time: 0,
    }
  }
}
impl RequestTimeSyncT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<RequestTimeSync<'b>> {
    let client_time = self.client_time;
    RequestTimeSync::create(_fbb, &RequestTimeSyncArgs{
      client_time,
    })
  }
}
