// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ResponseBattleEndOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ResponseBattleEnd<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ResponseBattleEnd<'a> {
  type Inner = ResponseBattleEnd<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ResponseBattleEnd<'a> {

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.ResponseBattleEnd"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ResponseBattleEnd { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    _args: &'args ResponseBattleEndArgs
  ) -> flatbuffers::WIPOffset<ResponseBattleEnd<'bldr>> {
    let mut builder = ResponseBattleEndBuilder::new(_fbb);
    builder.finish()
  }

  pub fn unpack(&self) -> ResponseBattleEndT {
    ResponseBattleEndT {
    }
  }
}

impl flatbuffers::Verifiable for ResponseBattleEnd<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct ResponseBattleEndArgs {
}
impl<'a> Default for ResponseBattleEndArgs {
  #[inline]
  fn default() -> Self {
    ResponseBattleEndArgs {
    }
  }
}

pub struct ResponseBattleEndBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ResponseBattleEndBuilder<'a, 'b> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ResponseBattleEndBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ResponseBattleEndBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ResponseBattleEnd<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ResponseBattleEnd<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ResponseBattleEnd");
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct ResponseBattleEndT {
}
impl Default for ResponseBattleEndT {
  fn default() -> Self {
    Self {
    }
  }
}
impl ResponseBattleEndT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<ResponseBattleEnd<'b>> {
    ResponseBattleEnd::create(_fbb, &ResponseBattleEndArgs{
    })
  }
}
