// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ResponseReconnectOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ResponseReconnect<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ResponseReconnect<'a> {
  type Inner = ResponseReconnect<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ResponseReconnect<'a> {
  pub const VT_GAME_STATE: flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.ResponseReconnect"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ResponseReconnect { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ResponseReconnectArgs
  ) -> flatbuffers::WIPOffset<ResponseReconnect<'bldr>> {
    let mut builder = ResponseReconnectBuilder::new(_fbb);
    builder.add_game_state(args.game_state);
    builder.finish()
  }

  pub fn unpack(&self) -> ResponseReconnectT {
    let game_state = self.game_state();
    ResponseReconnectT {
      game_state,
    }
  }

  #[inline]
  pub fn game_state(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ResponseReconnect::VT_GAME_STATE, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ResponseReconnect<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("game_state", Self::VT_GAME_STATE, false)?
     .finish();
    Ok(())
  }
}
pub struct ResponseReconnectArgs {
    pub game_state: i32,
}
impl<'a> Default for ResponseReconnectArgs {
  #[inline]
  fn default() -> Self {
    ResponseReconnectArgs {
      game_state: 0,
    }
  }
}

pub struct ResponseReconnectBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ResponseReconnectBuilder<'a, 'b> {
  #[inline]
  pub fn add_game_state(&mut self, game_state: i32) {
    self.fbb_.push_slot::<i32>(ResponseReconnect::VT_GAME_STATE, game_state, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ResponseReconnectBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ResponseReconnectBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ResponseReconnect<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ResponseReconnect<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ResponseReconnect");
      ds.field("game_state", &self.game_state());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct ResponseReconnectT {
  pub game_state: i32,
}
impl Default for ResponseReconnectT {
  fn default() -> Self {
    Self {
      game_state: 0,
    }
  }
}
impl ResponseReconnectT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<ResponseReconnect<'b>> {
    let game_state = self.game_state;
    ResponseReconnect::create(_fbb, &ResponseReconnectArgs{
      game_state,
    })
  }
}
