// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ServerBroadcastBattleLoadProgressOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ServerBroadcastBattleLoadProgress<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ServerBroadcastBattleLoadProgress<'a> {
  type Inner = ServerBroadcastBattleLoadProgress<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ServerBroadcastBattleLoadProgress<'a> {
  pub const VT_PLAYER_ID: flatbuffers::VOffsetT = 4;
  pub const VT_PROGRESS: flatbuffers::VOffsetT = 6;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.ServerBroadcastBattleLoadProgress"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ServerBroadcastBattleLoadProgress { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ServerBroadcastBattleLoadProgressArgs
  ) -> flatbuffers::WIPOffset<ServerBroadcastBattleLoadProgress<'bldr>> {
    let mut builder = ServerBroadcastBattleLoadProgressBuilder::new(_fbb);
    builder.add_player_id(args.player_id);
    builder.add_progress(args.progress);
    builder.finish()
  }

  pub fn unpack(&self) -> ServerBroadcastBattleLoadProgressT {
    let player_id = self.player_id();
    let progress = self.progress();
    ServerBroadcastBattleLoadProgressT {
      player_id,
      progress,
    }
  }

  #[inline]
  pub fn player_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ServerBroadcastBattleLoadProgress::VT_PLAYER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn progress(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ServerBroadcastBattleLoadProgress::VT_PROGRESS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ServerBroadcastBattleLoadProgress<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("player_id", Self::VT_PLAYER_ID, false)?
     .visit_field::<i32>("progress", Self::VT_PROGRESS, false)?
     .finish();
    Ok(())
  }
}
pub struct ServerBroadcastBattleLoadProgressArgs {
    pub player_id: u64,
    pub progress: i32,
}
impl<'a> Default for ServerBroadcastBattleLoadProgressArgs {
  #[inline]
  fn default() -> Self {
    ServerBroadcastBattleLoadProgressArgs {
      player_id: 0,
      progress: 0,
    }
  }
}

pub struct ServerBroadcastBattleLoadProgressBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ServerBroadcastBattleLoadProgressBuilder<'a, 'b> {
  #[inline]
  pub fn add_player_id(&mut self, player_id: u64) {
    self.fbb_.push_slot::<u64>(ServerBroadcastBattleLoadProgress::VT_PLAYER_ID, player_id, 0);
  }
  #[inline]
  pub fn add_progress(&mut self, progress: i32) {
    self.fbb_.push_slot::<i32>(ServerBroadcastBattleLoadProgress::VT_PROGRESS, progress, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ServerBroadcastBattleLoadProgressBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ServerBroadcastBattleLoadProgressBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ServerBroadcastBattleLoadProgress<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ServerBroadcastBattleLoadProgress<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ServerBroadcastBattleLoadProgress");
      ds.field("player_id", &self.player_id());
      ds.field("progress", &self.progress());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct ServerBroadcastBattleLoadProgressT {
  pub player_id: u64,
  pub progress: i32,
}
impl Default for ServerBroadcastBattleLoadProgressT {
  fn default() -> Self {
    Self {
      player_id: 0,
      progress: 0,
    }
  }
}
impl ServerBroadcastBattleLoadProgressT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<ServerBroadcastBattleLoadProgress<'b>> {
    let player_id = self.player_id;
    let progress = self.progress;
    ServerBroadcastBattleLoadProgress::create(_fbb, &ServerBroadcastBattleLoadProgressArgs{
      player_id,
      progress,
    })
  }
}
