// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ServerBroadcastBattleShouldFinishOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ServerBroadcastBattleShouldFinish<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ServerBroadcastBattleShouldFinish<'a> {
  type Inner = ServerBroadcastBattleShouldFinish<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ServerBroadcastBattleShouldFinish<'a> {
  pub const VT_SERVER_TIME: flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.ServerBroadcastBattleShouldFinish"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ServerBroadcastBattleShouldFinish { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ServerBroadcastBattleShouldFinishArgs
  ) -> flatbuffers::WIPOffset<ServerBroadcastBattleShouldFinish<'bldr>> {
    let mut builder = ServerBroadcastBattleShouldFinishBuilder::new(_fbb);
    builder.add_server_time(args.server_time);
    builder.finish()
  }

  pub fn unpack(&self) -> ServerBroadcastBattleShouldFinishT {
    let server_time = self.server_time();
    ServerBroadcastBattleShouldFinishT {
      server_time,
    }
  }

  #[inline]
  pub fn server_time(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ServerBroadcastBattleShouldFinish::VT_SERVER_TIME, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ServerBroadcastBattleShouldFinish<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("server_time", Self::VT_SERVER_TIME, false)?
     .finish();
    Ok(())
  }
}
pub struct ServerBroadcastBattleShouldFinishArgs {
    pub server_time: u64,
}
impl<'a> Default for ServerBroadcastBattleShouldFinishArgs {
  #[inline]
  fn default() -> Self {
    ServerBroadcastBattleShouldFinishArgs {
      server_time: 0,
    }
  }
}

pub struct ServerBroadcastBattleShouldFinishBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ServerBroadcastBattleShouldFinishBuilder<'a, 'b> {
  #[inline]
  pub fn add_server_time(&mut self, server_time: u64) {
    self.fbb_.push_slot::<u64>(ServerBroadcastBattleShouldFinish::VT_SERVER_TIME, server_time, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ServerBroadcastBattleShouldFinishBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ServerBroadcastBattleShouldFinishBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ServerBroadcastBattleShouldFinish<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ServerBroadcastBattleShouldFinish<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ServerBroadcastBattleShouldFinish");
      ds.field("server_time", &self.server_time());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct ServerBroadcastBattleShouldFinishT {
  pub server_time: u64,
}
impl Default for ServerBroadcastBattleShouldFinishT {
  fn default() -> Self {
    Self {
      server_time: 0,
    }
  }
}
impl ServerBroadcastBattleShouldFinishT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<ServerBroadcastBattleShouldFinish<'b>> {
    let server_time = self.server_time;
    ServerBroadcastBattleShouldFinish::create(_fbb, &ServerBroadcastBattleShouldFinishArgs{
      server_time,
    })
  }
}
