// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ServerBroadcastBattleStartedOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ServerBroadcastBattleStarted<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ServerBroadcastBattleStarted<'a> {
  type Inner = ServerBroadcastBattleStarted<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ServerBroadcastBattleStarted<'a> {
  pub const VT_START_SERVER_TIME: flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.ServerBroadcastBattleStarted"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ServerBroadcastBattleStarted { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ServerBroadcastBattleStartedArgs
  ) -> flatbuffers::WIPOffset<ServerBroadcastBattleStarted<'bldr>> {
    let mut builder = ServerBroadcastBattleStartedBuilder::new(_fbb);
    builder.add_start_server_time(args.start_server_time);
    builder.finish()
  }

  pub fn unpack(&self) -> ServerBroadcastBattleStartedT {
    let start_server_time = self.start_server_time();
    ServerBroadcastBattleStartedT {
      start_server_time,
    }
  }

  #[inline]
  pub fn start_server_time(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ServerBroadcastBattleStarted::VT_START_SERVER_TIME, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ServerBroadcastBattleStarted<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("start_server_time", Self::VT_START_SERVER_TIME, false)?
     .finish();
    Ok(())
  }
}
pub struct ServerBroadcastBattleStartedArgs {
    pub start_server_time: u64,
}
impl<'a> Default for ServerBroadcastBattleStartedArgs {
  #[inline]
  fn default() -> Self {
    ServerBroadcastBattleStartedArgs {
      start_server_time: 0,
    }
  }
}

pub struct ServerBroadcastBattleStartedBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ServerBroadcastBattleStartedBuilder<'a, 'b> {
  #[inline]
  pub fn add_start_server_time(&mut self, start_server_time: u64) {
    self.fbb_.push_slot::<u64>(ServerBroadcastBattleStarted::VT_START_SERVER_TIME, start_server_time, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ServerBroadcastBattleStartedBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ServerBroadcastBattleStartedBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ServerBroadcastBattleStarted<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ServerBroadcastBattleStarted<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ServerBroadcastBattleStarted");
      ds.field("start_server_time", &self.start_server_time());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct ServerBroadcastBattleStartedT {
  pub start_server_time: u64,
}
impl Default for ServerBroadcastBattleStartedT {
  fn default() -> Self {
    Self {
      start_server_time: 0,
    }
  }
}
impl ServerBroadcastBattleStartedT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<ServerBroadcastBattleStarted<'b>> {
    let start_server_time = self.start_server_time;
    ServerBroadcastBattleStarted::create(_fbb, &ServerBroadcastBattleStartedArgs{
      start_server_time,
    })
  }
}
