// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ServerBroadcastBattleActionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ServerBroadcastBattleAction<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ServerBroadcastBattleAction<'a> {
  type Inner = ServerBroadcastBattleAction<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ServerBroadcastBattleAction<'a> {
  pub const VT_SERVER_TIME: flatbuffers::VOffsetT = 4;
  pub const VT_ACTIONS: flatbuffers::VOffsetT = 6;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.ServerBroadcastBattleAction"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ServerBroadcastBattleAction { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ServerBroadcastBattleActionArgs<'args>
  ) -> flatbuffers::WIPOffset<ServerBroadcastBattleAction<'bldr>> {
    let mut builder = ServerBroadcastBattleActionBuilder::new(_fbb);
    builder.add_server_time(args.server_time);
    if let Some(x) = args.actions { builder.add_actions(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> ServerBroadcastBattleActionT {
    let server_time = self.server_time();
    let actions = self.actions().map(|x| {
      x.iter().map(|t| t.unpack()).collect()
    });
    ServerBroadcastBattleActionT {
      server_time,
      actions,
    }
  }

  #[inline]
  pub fn server_time(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ServerBroadcastBattleAction::VT_SERVER_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn actions(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<BattleAction<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<BattleAction>>>>(ServerBroadcastBattleAction::VT_ACTIONS, None)}
  }
}

impl flatbuffers::Verifiable for ServerBroadcastBattleAction<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("server_time", Self::VT_SERVER_TIME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<BattleAction>>>>("actions", Self::VT_ACTIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct ServerBroadcastBattleActionArgs<'a> {
    pub server_time: u64,
    pub actions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<BattleAction<'a>>>>>,
}
impl<'a> Default for ServerBroadcastBattleActionArgs<'a> {
  #[inline]
  fn default() -> Self {
    ServerBroadcastBattleActionArgs {
      server_time: 0,
      actions: None,
    }
  }
}

pub struct ServerBroadcastBattleActionBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ServerBroadcastBattleActionBuilder<'a, 'b> {
  #[inline]
  pub fn add_server_time(&mut self, server_time: u64) {
    self.fbb_.push_slot::<u64>(ServerBroadcastBattleAction::VT_SERVER_TIME, server_time, 0);
  }
  #[inline]
  pub fn add_actions(&mut self, actions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<BattleAction<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ServerBroadcastBattleAction::VT_ACTIONS, actions);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ServerBroadcastBattleActionBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ServerBroadcastBattleActionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ServerBroadcastBattleAction<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ServerBroadcastBattleAction<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ServerBroadcastBattleAction");
      ds.field("server_time", &self.server_time());
      ds.field("actions", &self.actions());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct ServerBroadcastBattleActionT {
  pub server_time: u64,
  pub actions: Option<Vec<BattleActionT>>,
}
impl Default for ServerBroadcastBattleActionT {
  fn default() -> Self {
    Self {
      server_time: 0,
      actions: None,
    }
  }
}
impl ServerBroadcastBattleActionT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<ServerBroadcastBattleAction<'b>> {
    let server_time = self.server_time;
    let actions = self.actions.as_ref().map(|x|{
      let w: Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();_fbb.create_vector(&w)
    });
    ServerBroadcastBattleAction::create(_fbb, &ServerBroadcastBattleActionArgs{
      server_time,
      actions,
    })
  }
}
